# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT

# Enable nice!view displays.
CONFIG_ZMK_DISPLAY=y

# Uncomment these two lines to add support for encoders
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment this line below to add rgb underglow / backlight support
# CONFIG_ZMK_RGB_UNDERGLOW=y

# CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
